# Data

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lukeconibear/intro_ml/blob/main/docs/02_data.ipynb)

In [1]:
# if you're using colab, then install the required modules
import sys
IN_COLAB = 'google.colab' in sys.modules
if IN_COLAB:
    %pip install ...

In [61]:
import numpy as np
import tensorflow as tf
import torch

In [62]:
np.random.normal(size=(1,))

array([-0.60170661])

In [63]:
tf.random.normal(shape=(1,))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.9826471], dtype=float32)>

In [65]:
np.random.normal(size=(3,))

array([ 1.85227818, -0.01349722, -1.05771093])

In [66]:
tf.random.normal(shape=(3,))

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.7847413, -0.5809721, -0.2452356], dtype=float32)>

In [68]:
np.random.normal(size=(3, 3))

array([[ 0.82254491, -1.22084365,  0.2088636 ],
       [-1.95967012, -1.32818605,  0.19686124],
       [ 0.73846658,  0.17136828, -0.11564828]])

In [69]:
tf.random.normal(shape=(3, 3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.2764754 , -0.6551445 , -0.00389835],
       [ 0.45862213, -1.507044  ,  1.0932531 ],
       [-0.45938343, -0.35318485, -0.3738681 ]], dtype=float32)>

- datasets
- data centric AI hub videos
- efficient feeding of data into GPUs
- pipelines for large data I/O into GPUs using compression/decompression, Ray datasets




### Synthetic data

...

- [NVIDIA Replicator Composer](https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/tutorial_replicator_composer.html#replicator-composer)

In [ ]:
import tensorflow as tf

Check whether you have a GPU:

In [ ]:
if tf.config.list_physical_devices('GPU'):
    print(f"Yes, there are {len(tf.config.list_physical_devices('GPU'))} GPUs available.")
else:
    print('No, GPUs are not available.')

## Exercises

```{admonition} Exercise 1

...

```

## {ref}`Solutions <data>`

## Key Points

```{important}

- [x] _..._

```

## Further information

### Good practices

- ...

### Other options

- ...
 
### Resources

- [TensorFlow official datasets](https://www.tensorflow.org/datasets)
    - Datasets ready to use with TensorFlow.
- [Google research datasets](https://ai.google/tools/datasets/)
    - Large-scale datasets across computer science.
- [Google Dataset Search](https://datasetsearch.research.google.com/)
- [Google Cloud public datasets](https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset&pli=1)
- [Kaggle Datasets](https://www.kaggle.com/datasets)
- [Torch Vision Datasets](https://pytorch.org/vision/stable/datasets.html)
- [Papers with code - Datasets](https://paperswithcode.com/datasets)
- [HuggingFace - Datasets](https://huggingface.co/datasets)